# Site
repository: yunjiewuw/yunjiewuw.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Christina Yun-Jie Wu
title: Data Analyst
email: cyjwuwwwww@gmail.com
wwebsite: www.github.com/yunjiewuw/

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: christina_jie
github_username:  yunjiewuw
instagram_username: christina_yunjie
linkedin_username: yun-jie-christina-wu

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://vocus.cc/user/@yunjie_christina
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Christina and I'm a new graduate passionated and skilled in insight mining through data analysis.
  A Fast-learning with a blending business insight and scientific critical thinking. Showcases strong self-learning and discipline by effectively managing research projects and accumulating insightful business investment observations.  

  I am most skilled in: <mark>python</mark> and <mark>SQL</mark> 

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: E-commerce data analysis
        link: github.com/yunjiewuw/Ecommerce_Transaction_Database_Analysis
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          The project aims to provide valuable business insights to an e-commerce firm by analyzing transaction data from 2019 (Kaggle Database). 
        description: | # this will include new lines to allow paragraphs
          The analysis includes various aspects and skillsets, such as: 
          - EDA: Revenue differences between new and old customers, customer demo distribution under different coupon usages, etc
          - Predicting customer lifetime value 
          - Identifying potential sales bundles
          - Segmenting customers using both heuristic and machine learning techniques. Leveraging transaction, tax, and spend datasets, this project serves as a foundation for deriving actionable business strategies.The attempt of conducting business stragetic insights to ecommerce transaction data
          
          skill sets: <mark> supervised/unsupervised ML </mark>
  
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Hung-Tse Invesment
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Venture Capital Analysis (Part-time )
        caption: Sept 2023 - Jan 2024
        quote: >
          Business Insights, Analytic and Communication Skills

        description: | # this will include new lines to allow paragraphs
          - Deal sourcing 20+ startup companies, organizing and hosting 7+ con-calls based in Taiwan. 
          - Conducted 2 comprehensive due diligence on B2B companies, assessing potential investment opportunities from financial, business strategic, product competition, and team perspectives on content creation market, 3 PL Logistic sectors. 
          - Managed account responsibilities for 1/3 of the portfolio, focusing market and business analysis, and evaluation of B2B and B2B2C go-to-market strategies
          - Co-directed stakeholder relations through proactive communication and support to portfolio companies

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: National Taiwan University, Taiwan
        caption: 2021 - 2024
        sub_title: MS Psychology, Neuroscience
        quote: >
          Relevant skills: Experimental Design, Programming in Python (A+), Multivariate Analysis (A+), Critical thinking
        description: | # this will include new lines to allow paragraphs
          - Led end-to-end execution of neuroimaging experiments, from code development to data structure design, ensuring synchronization with scanner triggers for maximal data precision.
          - Applied advanced Python libraries including Scikit-learn, Pandas, NumPy, and OS for thorough preprocessing and cleaning of extensive datasets, guaranteeing data integrity for subsequent analysis.
          - Conducted General Linear Model (GLM) regression analysis on complex neuroimaging datasets, extracting beta brain patterns across mega data (238,955 brain voxels at 1274 timepoints across 20+ subjects) 
          - Employed multivariate analysis techniques to assess brain activation similarity under varying conditions, driving hypothesis testing and uncovering crucial neural-cognitive relationships in neuroscience research.
          - Impactful scientific journal publication (pending)

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in data-based insight-mining 
      - Watch animal reels
      - Wandering (both physcial and mental)and Journaling
      - Traveling and Vlogging
      - Life question philosopher

      - Check out my YouTube and Reels where I will upload my Vlogs  
      ["YouTube"](https://youtube.com/@user-lo2cr4cs4n?si=tbV7e1boPclhxnFv)
      - Also check out my Blog or Twitter to see what's on my mind these days...  
      ["Blog Post"] (https://vocus.cc/user/@yunjie_christina)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
