# Site
repository: yunjiewuw/yunjiewuw.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Christina Yun-Jie Wu
title: Data Analyst
email: cyjwuwwwww@gmail.com
website: www.github.com/yunjiewuw/yunjiewuw.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: christina_jie
github_username:  yunjiewuw
instagram_username: christina_yunjie
linkedin_username: yun-jie-christina-wu

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Christina and I'm a new graduate skilled in data analysis.
  A Fast-learning with a blending business insight and scientific critical thinking. Showcases strong self-learning and discipline by effectively managing research projects and accumulating insightful business investment observations.  

  I am most skilled in: <mark>python</mark> and <mark>SQL</mark> Data Analysis

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: E-commerce data analysis
        link: github.com/yunjiewuw/Ecommerce_Transaction_Database_Analysis
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          The attempt of conducting business stragetic insights to ecommerce transaction data
        description: | # this will include new lines to allow paragraphs
          EDA, LTV prediction, customer segregation, sales bundle prediction, Next purchase range prediction. <mark> supervised/unsupervised ML </mark>
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Hung-Tse Invesment
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Venture Capital Analysis (Part-time )
        caption: Sept 2023 - Jan 2024
        quote: >
          Deal sourcing 20+ startup companies, organizing and hosting 7+ con-calls based in Taiwan. 
          Conducted 2 comprehensive due diligence on B2B companies, assessing potential investment opportunities from financial, business strategic, product competition, and team perspectives on content creation market, 3 PL Logistic sectors. 
          Managed account responsibilities for 1/3 of the portfolio, focusing market and business analysis, and evaluation of B2B and B2B2C go-to-market strategies
          Co-directed stakeholder relations through proactive communication and support to portfolio companies

        description: | # this will include new lines to allow paragraphs
          think think think (Everyday)

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: National Taiwan University, Taiwan
        caption: 2021 - 2024
        sub_title: MS Psychology, Neuroscience
        quote: >
          Relevant skills: Experimental Design, Programming in Python (A+), Multivariate Analysis (A+), Critical thinking
        description: | # this will include new lines to allow paragraphs
          Managed experimental projects and made scientific publication (pending)

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in data-based insight-mining 
      - watch animal reels
      - Wandering (both physcial and mental)
      - Traveling and Vlogging

      Look at this cool image  
      ![Trees](/yunjiewuw.github.io/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: yunjiewuw/yunjiewuw.github.io

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
